### ISSUE TITLE
Replace Tyk binary with apt-get installation from package cloud

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk-hybrid-docker#4]
The current approach is too fragile and adds human error factor. It makes whole process easier as well.

**Comment by lonelycode** [comment]
Would prefer to be able to push a build from a binary repo instead of PackageCloud, or generate a pipeline that builds a PR, we need to be able to shift hybrid in line with cloud, so the build numbers will not be lockstep with on-prem.

(e.g. we need to fix a hybrid only issue, does not need a full PC release)

**Comment by buger** [comment]
Done
